NICHES = [
 # Kyle's own named niches
 ("junk removal","junk removal"),
 ("epoxy garage floor","epoxy garage floor"),
 ("popcorn ceiling removal","popcorn ceiling removal"),
 ("septic tank pumping","septic tank pumping"),
 ("towing service","towing service"),
 ("auto glass repair","auto glass repair"),
 ("gutter installation","gutter installation"),
 # adjacent obscure, high ticket, low franchise
 ("chimney sweep","chimney sweep"),
 ("crawl space encapsulation","crawl space encapsulation"),
 ("asbestos removal","asbestos removal"),
 ("dumpster rental","dumpster rental"),
 ("stump grinding","stump grinding"),
 ("pool resurfacing","pool resurfacing"),
 ("driveway sealing","driveway sealing"),
 ("concrete leveling","concrete leveling"),
 ("spray foam insulation","spray foam insulation"),
 ("attic insulation removal","attic insulation removal"),
 ("paver patio installation","paver patio installation"),
 ("artificial turf installation","artificial turf installation"),
 ("retaining wall contractor","retaining wall contractor"),
 ("french drain installation","french drain installation"),
 ("basement waterproofing","basement waterproofing"),
 ("radon mitigation","radon mitigation"),
 ("dryer vent cleaning","dryer vent cleaning"),
 ("air duct cleaning","air duct cleaning"),
 ("window tinting","window tinting"),
 ("cabinet refinishing","cabinet refinishing"),
 ("bathtub refinishing","bathtub refinishing"),
 ("hardwood floor refinishing","hardwood floor refinishing"),
 ("pressure washing","pressure washing"),
 ("roof cleaning","roof cleaning"),
 ("wildlife removal","wildlife removal"),
 ("hoarding cleanup","hoarding cleanup"),
 ("biohazard cleanup","biohazard cleanup"),
 ("fire damage restoration","fire damage restoration"),
 ("fence installation","fence installation"),
 ("asphalt paving","asphalt paving"),
 ("well pump repair","well pump repair"),
 ("water softener installation","water softener installation"),
 ("generator installation","generator installation"),
 ("ev charger installation","ev charger installation"),
 ("paintless dent repair","paintless dent repair"),
 ("mobile mechanic","mobile mechanic"),
 ("piano moving","piano movers"),
 ("hot tub removal","hot tub removal"),
 ("tuckpointing","tuckpointing"),
 ("stucco repair","stucco repair"),
 ("siding repair","siding repair"),
 ("sod installation","sod installation"),
 ("land clearing","land clearing"),
]
